server:
  port: 20000

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
